Code:
#pragma config(Motor,  port1,           LeftMotor1,           tmotorNormal)
#pragma config(Motor,  port2,           RightMotor1,          tmotorNormal)
#pragma config(Motor,  port7,           LeftMotor2,           tmotorNormal)
#pragma config(Motor,  port8,           RightMotor2,          tmotorNormal)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
  bMotorFlippedMode[LeftMotor1] = 1;
  bMotorFlippedMode[LeftMotor2] = 1;
  bVexAutonomousMode = false;
  while (true) {
    motor[LeftMotor1]  = vexRT[Ch3] + vexRT[Ch4];
    motor[RightMotor1] = vexRT[Ch3] - vexRT[Ch4];
    motor[LeftMotor2]  = vexRT[Ch3] + vexRT[Ch4];
    motor[RightMotor2] = vexRT[Ch3] - vexRT[Ch4];
    wait1Msec(10);
  }
}
